paths:
  images: /home/anna/Pictures/pool/bags/0036SET/000
  warp_matrices: /home/anna/code/process_multispectral_images/out/warp_matrices_reference
  panel_image_nr: "0001"
  output: /home/anna/Pictures/pool/bags/out/9:00

params:
  altitude_change: 50
  image_numbers: [4, 6, 10, 12, 18, 19]

# ${hydra:runtime.cwd}    
