paths:
  images: /home/anna/Pictures/pool/ghost_net/0045SET/000
  warp_matrices: /home/anna/code/process_multispectral_images/out/warp_matrices_reference
  panel_image_nr: "0000"
  output: /home/anna/Pictures/pool/ghost_net/out/10:00
  channels_output: /home/anna/Pictures/annotation/ghost_net_10/

params:
  altitude_change: 59
  image_numbers: [11,12,14,15,16,17,20]
