paths:
  images: /home/anna/Pictures/pool/bags/0035SET/000
  warp_matrices: /home/anna/code/process_multispectral_images/out/warp_matrices_reference
  panel_image_nr: "0000"
  output: /home/anna/Pictures/pool/bags/out/15:00

params:
  altitude_change: 45
  image_numbers: [4, 7, 9, 14, 17, 19]
