paths:
  images: /home/anna/Pictures/pool/bags/0041SET/000
  warp_matrices: /home/anna/code/process_multispectral_images/out/warp_matrices_reference
  panel_image_nr: "0000"
  output: /home/anna/Pictures/pool/bags/out/12:00

params:
  altitude_change: 35
  image_numbers: [1, 2, 3, 5, 8, 9]